name: Trigger auto deployment for sdfagsdfh

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/sdfagsdfh-AutoDeployTrigger-a54001a6-6184-4a97-ba71-0a31ac7fe5c2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: michieltestreg.azurecr.io
          username: ${{ secrets.SDFAGSDFH_REGISTRY_USERNAME }}
          password: ${{ secrets.SDFAGSDFH_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: michieltestreg.azurecr.io/sdfagsdfh:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SDFAGSDFH_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sdfagsdfh -g lz-container-app --server michieltestreg.azurecr.io --username  ${{ secrets.SDFAGSDFH_REGISTRY_USERNAME }} --password ${{ secrets.SDFAGSDFH_REGISTRY_PASSWORD }}
            az containerapp update -n sdfagsdfh -g lz-container-app --image michieltestreg.azurecr.io/sdfagsdfh:${{ github.sha }}
